# Generated by Django 3.2.8 on 2022-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.CharField(max_length=500, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url_title',
            field=models.CharField(max_length=500, verbose_name='عنوان لینک'),
        ),
    ]
