# Generated by Django 3.2.8 on 2022-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_auto_20220318_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال؟'),
        ),
    ]
