# Generated by Django 3.2.8 on 2022-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_slider_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='لینک'),
        ),
    ]
