# Generated by Django 3.2.8 on 2022-03-27 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 3, 27), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
