# Generated by Django 3.2.8 on 2022-07-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرهای مقاله'},
        ),
    ]
