# Generated by Django 3.2.8 on 2022-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_auto_20220212_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='تصویر اواتار'),
        ),
    ]
