# Generated by Django 3.2.8 on 2022-03-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_user_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/profile', verbose_name='تصویر اواتار'),
        ),
    ]
